dist: trusty
sudo: false
language: cpp
os: debian-latest
env: arm

script:
  - pip install conan
 #- sudo apt-get install git git-core
 #- git clone git://git.drogon.net/wiringPi
 #- cd wiringPi
 #- ./build
  - cmake .
  - cmake --build . -- -j2
